language: php

php:
  - "5.5"
  - "5.4"
  - "5.3"

script:
 - phpunit --coverage-text
 - output=$(php php-cs-fixer.phar fix -v --dry-run --level=psr2 src); if [[ $output ]]; then while read -r line; do echo -e "\e[00;31m$line\e[00m"; done <<< "$output"; false; fi;

notifications:
  email: false
